---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(DT)
library(varhandle)
library(magrittr)
library(sp)
library(leaflet)
library(dplyr)
```

```{r}
jobs=read.csv('../data/job.csv')
jobs$score[is.na(jobs$score)] <- 99
jobs <- jobs[jobs$zip>10000,]
jobs <- jobs[is.na(jobs$Salary.Range.From) == FALSE,]
```

```{r}
head(jobs)
```

```{r}
load('../data/subdat.RData')

labels_sales <- sprintf(
  "Zip Code: <strong>%s</strong><br/>Average Annual Salary (AAS): <strong>$%g/yr<sup></sup></strong>",
  as.character(subdat$ZIPCODE), subdat$value
) %>% lapply(htmltools::HTML)

zips=read.csv("../data/zips2.csv",stringsAsFactors = F)

subdat$ZIPCODE=zips$zip[52:102]
#subdat$zip=zips2$zip[52:109]
subdat$value=zips$maxsala[52:102]

```


```{r}
category=c("Administration","Building","Clerical","Communications","Community","Constituent","Engineering","Finance","Health","Information","Legal","Maintenance","Policy","Public","Social","Technology")

jobs=read.csv('../data/job.csv', header=TRUE)
subway <- read.csv('../data/subwayinfo.csv', header=TRUE)
bar <- read.csv('../data/Bars.csv', header=TRUE)
bus <- read.csv('../data/bus_stop.csv', header=TRUE)
Cinema <- read.csv('../data/theatre_dxy.csv', header=TRUE)
trans_time <- read.csv('../data/trans_time1.csv', header=TRUE)

subway$on <- 1
bus$on <- 1
Cinema$on <- 1
```

```{r}

ui=fluidPage(includeCSS("../app/style.css"),navbarPage(p(class="h","JobsSmart"),id = "inTabset",
  tabPanel("All about Jobs",
           leafletOutput("mymap",height = 1000)),
  tabPanel("Recommendation",
           sidebarPanel(
            sliderInput("slider1",label = h3("maximum Annual Salary")
                        ,min=20000,max=250000,value=c(10000,20000))),
            selectInput("variable", "Variable:",
                c("Policy & Regulation" = "Policy & Regulation", 
                  "Engineering" = "Engineering", "Database" = "Database", 
                  "Legal" = "Legal", "Communication & Writing" = "Communication & Writing",
                  "Systems & Technology" = "Systems & Technology", 
                  "Leadership" = "Leadership", "Teamwork" = "Teamwork",
                  "Data Analysis" = "Data Analysis", 
                  "Microsoft Office" = "Microsoft Office")),
            selectInput("crime", "Crime:",
                c("Low" = '18', 
                  "Medium" = '30', 
                  "High" = '99', 
                  "All" = 'NA')),
           checkboxGroupInput("map_select", "Select:",
                c("Subway" = '1',
                  "Bus" = '2',
                  "Cinema" = '3'
                  )),
           textInput('zip_input', "Zip:"),
            selectInput("speech1","Choose a job category" ,category
                              )
           ),
  
  # Main panel for displaying outputs ----
   mainPanel(tags$head(tags$style("#NYC_jobs {white-space: nowrap;}")),
            dataTableOutput("NYC_jobs"),leafletOutput("mymap2",height = 1000))
))
server=function(input, output) {
  output$mymap <- renderLeaflet({
   m <- leaflet(data = subdat) %>%
          addTiles() %>%
          setView(lng=-73.98928, lat = 40.75042 , zoom =12)%>%
          addProviderTiles("Stamen.TonerLite")})
      pal <- colorNumeric(
       palette = "Purples",
       domain = subdat$value
       )
     leafletProxy("mymap",data=subdat)%>%
       addPolygons(layerId = ~ZIPCODE,
                   stroke = T, weight=1,
                   fillOpacity = 0.95,
                   color = ~pal(value),
                   highlightOptions = highlightOptions(color='#ff0000', opacity = 0.5, weight = 4, fillOpacity = 0.9,bringToFront = TRUE, sendToBack = TRUE),label = labels_sales,
        labelOptions = labelOptions(
          style = list("font-weight" = "normal", padding = "3px 8px"),
          textsize = "15px",
          direction = "auto"))%>%
addLegend(pal = pal, values = ~value, opacity = 1)
     minsala=jobs$Salary.Range.From
  maxsala=jobs$Salary.Range.To
  
  output$NYC_jobs=renderDataTable(
    merge(jobs%>%filter(minsala>input$slider1[1] & maxsala<input$slider1[2]&
      jobs$'score' <= input$crime & jobs$'Main.Skill'==input$variable & jobs$'Department' == input$'speech1'), trans_time[,c('X',paste('X',input$'zip_input',sep=""))], by.x='zip', by.y='X')  
    ,options = list(pageLength=5, scrollX = TRUE, scrollY = TRUE
  ))
  
  output$mymap2 <- renderLeaflet({
   m <- leaflet(data=jobs) %>%
          addTiles() %>%
          setView(lng=-73.98928, lat=40.75042 , zoom=17)%>%
          addProviderTiles("Stamen.TonerLite")%>%

     addMarkers(lng = ~bus[bus$on == ifelse((2 %in% input$map_select),1,0),]$LONGITUDE,
                     lat = ~bus[bus$on == ifelse((2 %in% input$map_select),1,0),]$LATITUDE,
                     icon = list(iconUrl='../lib/bus.png',iconSize=c(15,15)))%>%
      addMarkers(lng = ~(Cinema[Cinema$on == ifelse((3 %in% input$map_select),1,0),])$lon,
                     lat = ~(Cinema[Cinema$on == ifelse((3 %in% input$map_select),1,0),])$lat,
                     icon = list(iconUrl='../lib/Movie.png',iconSize=c(15,15)))%>%
      addMarkers(lng = ~(subway[subway$on == ifelse((1 %in% input$map_select),1,0),])$Station.Longitude,
                     lat = ~(subway[subway$on ==ifelse((1 %in% input$map_select),1,0),])$Station.Latitude,
                     icon = list(iconUrl='../lib/metro.png',iconSize=c(15,15)))%>%
      addCircleMarkers(lng = ~ (jobs%>%filter(minsala>input$slider1[1] & maxsala<input$slider1[2]&
      jobs$'score' <= input$crime & jobs$'Main.Skill'==input$variable & jobs$'Department' == input$'speech1')) $geocodes.lon,
                     lat = ~(jobs%>%filter(minsala>input$slider1[1] & maxsala<input$slider1[2]&
      jobs$'score' <= input$crime & jobs$'Main.Skill'==input$variable & jobs$'Department' == input$'speech1') )$geocodes.lat,
                    stroke = FALSE, fillOpacity = 0.5
                     )
     
   m
 })
  

}
shinyApp(ui, server)


```